import { useEffect, useState } from "react";
import type { AdminProps } from "./types";
import { useAdminFetch } from "../hooks/useAdminFetch";

export default function AdminTrust({ token, toast }: AdminProps) {
  const fetchAdmin = useAdminFetch(token);
  const [data, setData] = useState<any>(null);
  const [scores, setScores] = useState<any[]>([]);
  useEffect(() => { void Promise.all([fetchAdmin("/api/admin/insights"), fetchAdmin("/api/trust/admin/users")]).then(([insights, trustScores]) => { setData(insights); setScores(Array.isArray(trustScores) ? trustScores : []); }).catch((err) => toast({ title: "Could not load trust data", description: err.message, variant: "destructive" })); }, [fetchAdmin, toast]);
  return <section className="space-y-5 rounded-xl border border-border/70 bg-background p-5 shadow-sm"><div><h2 className="text-sm font-semibold">Trust intelligence</h2><p className="mt-1 text-xs text-muted-foreground">Trust Score is the earned UTI /100. Creator Level is the canonical label derived from it.</p></div><div className="overflow-x-auto rounded-lg border border-border/60"><table className="w-full text-left text-xs"><thead className="bg-muted/30 text-muted-foreground"><tr><th className="px-3 py-2">User</th><th className="px-3 py-2">Score</th><th className="px-3 py-2">Level</th><th className="px-3 py-2">CVS</th><th className="px-3 py-2">BCS</th><th className="px-3 py-2">CTS</th><th className="px-3 py-2">CIS</th></tr></thead><tbody className="divide-y divide-border/60">{scores.map((score) => <tr key={score.id}><td className="px-3 py-2">#{score.userId}</td><td className="px-3 py-2 font-semibold">{Math.round(score.uti ?? 0)}</td><td className="px-3 py-2">{score.creatorLevel ?? "new_voice"}</td><td className="px-3 py-2">{Math.round(score.cvs ?? 0)}</td><td className="px-3 py-2">{Math.round(score.bcs ?? 0)}</td><td className="px-3 py-2">{Math.round(score.cts ?? 0)}</td><td className="px-3 py-2">{Math.round(score.avgCis ?? 0)}</td></tr>)}</tbody></table></div><pre className="max-h-[20rem] overflow-auto rounded-lg bg-muted/30 p-4 text-xs leading-6 text-muted-foreground">{data ? JSON.stringify(data, null, 2) : "Loading..."}</pre></section>;
}